### PR TITLE
Retry downloads a maximum of three times on temporary network errors

### PR DESCRIPTION
**Pull request by crawsible**
This PR is the first part of a response to https://github.com/pivotal-cf/pivnet-resource/issues/38. It retries downloads a maximum on three times when attempts to download product files via the client throw temporary network errors.

@zachgersh, do you have any examples of specific EOFs errors you're seeing? My understanding is that `io.Copy` won't ever throw an `io.EOF` because that's how `Reader`s and `WriterTo`s know the operation is over. Are you maybe seeing `io.ErrUnexpectedEOF`s?

NB: This PR includes a change to the lifecycle acceptance test that allows it to support `product-files`-inclusive `s3_filepath_prefix`es. This may require the inclusion of `product_files` to the front of your CI's `s3_filepath_prefix` (though my belief is that it will not).

- Have you made this pull request to the `develop` branch?
Yes.

- Have you [run the tests locally](https://github.com/pivotal-cf/pivnet-resource#running-the-tests)?
Yes.

### CODE REVIEW

**Comment by crawsible** [comment]
Also @robdimsdale, there's no log message [in the retry case](https://github.com/pivotal-cf/pivnet-resource/pull/44/commits/58826cd170ba3462f8dd49fdf94fb7335b8b0ce1#diff-5454fa6fc1099568a270def73a74e4ceR95). What do you think the log level would be there? I was thinking Info, since it seems like generally useful information (you know if your download is going to take longer because it's had to start over).

**Comment by robdimsdale** [comment]
Looking good! I would probably invert the logic of the loop in `downloadProductFileWithRetries` to return `err` as soon as possible, rather than the `continue`/`break`/`return nil`/`return err`. This probably looks something like `if netErr, ok := err.(net.Error); ok {} else {return err}`.

This should also make it easy to drop in log lines in both places. I'd suggest info for the "retry" and probably debug for the failure case because the error will be propagated up and logged at the top-level.

Also, how did you generate the `FakeNetError`? Could you add a counterfeiter `go generate` comment so we can reliably reproduce this? No worries if not, we can add that.

**Comment by zachgersh** [comment]
I think this looks really good as well! for the net.Error I'd actually go the other way and remove the fake entirely. I normally just define the net.Error so I essentially get something like this:

```go
type NetError struct {
   error
}

func(ne NetErrof) Temporary() bool {
  return true
}

myError := NetError{errors.New("explosions")}
...
```

I think you have to define Timeout as well but it is far shorter and there isn't really a need for such a large fake :dancing_men: 

@crawsible to your other question - I believe you are correct and we should guard against either of them. I believe io.EOF is still an error in some circumstances.

**Comment by crawsible** [comment]
Cool, I'll make that loop logic refactor and add the logging. I think when I add the `io.ErrUnexpectedEOF` handling your preferred loop might be a little wonky. I'll do my best and look forward to your feedback :)

I generated the `FakeNetError` by creating a one-off interface and then deleting it. `counterfeiter` can't handle `counterfeiter net.Error` because it isn't aware of the builtin interface `error`, which is composed into `net.Error`. Since it really *is* just a fake of `net.Error` I felt it'd be wrong to create an arbitrary file just to duplicate that interface without composition.

I'm perfectly happy to implement net.Error by hand in the tests, though I don't think I saw that pattern of implementing interfaces in tests anywhere else in the codebase (didn't look that hard though). The mock needs to implement `Error() string`, `Timeout() bool`, and `Temporary() bool`.

**Comment by crawsible** [comment]
I updated this branch:

1. rebased against develop (above the `release_uploader_test` fix)
1. replaced the counterfeited `FakeNetError` with a `net.Error` implementation in the downloader test file
1. added retry logic for `io.ErrUnexpectedEOF` errors as well
1. added logging for the different control flows

**Comment by robdimsdale** [comment]
Looks great, thanks! I made a couple of aesthetic changes mysql, rather than ask you to do them.

The PR is much appreciated, @crawsible, thank you. Also thanks to @zachgersh for reviews and suggestions.

**Pull request merged**
